name: Debian Packer Example

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  deb-control-file-build:
    name: Generate Debian Package
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Control File
        id: control-gen
        uses: Nightwind-Developments/debian-control-file-builder@latest
        with:
          config-file: 'examples/control_file_generate/example_control_template.json'
          deps-file: 'examples/control_file_generate/dependencies.txt'
          output-path: 'examples/input_example/'

      - name: Prints Output File Path
        run: echo "${{ steps.control-gen.outputs.control_file_path }}"

      - name: Confirms Control File is Present
        run: ls ${{ steps.control-gen.outputs.control_file_path }}

      #- name: Copies control File to Intended Location
      #  run: cp ${{ steps.control-gen.outputs.control_file_path }} examples/input_example

      - name: Prints Contents of Input Resources
        run: ls -l examples/input_example/

      - name: Build Docker Container & Run Debian Packer
        uses: ./
        id: container
        with:
          input_dir: 'examples/input_example'
          output_dir: 'output'
          layout_map_file: 'examples/example-map.json'
          package_name: 'HelloWorld'
          package_version: '1.0.0'
          package_arch: 'all'

      - name: Upload Generated Package File
        uses: actions/upload-artifact@v4
        with:
          name: generated-hello-world-package
          path: "${{ steps.container.outputs.generated_package_path }}"
          if-no-files-found: error
